# Generated by Django 3.1.4 on 2020-12-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201205_0141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categoria',
        ),
    ]
